### ISSUE TITLE
SECURITY: Indexierung verhindern

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_dsj#19]
Der DSJ wünscht keine Indexierung bei Internet-Suchmaschinen. Dies soll potenziellen Angreiffer:innen erschweren ihre Hitobitoinstanz zu finden. Um dies zu erreichen muss ein robotos.txt-File mit entsprechendem Inhalt erstellt werden.
Die Indexierung soll lediglich für den DSJ verhindert werden. Bei den restlichen Instanzen bleibt diese weiterhin bestehen.
Der Release erfolgt erst mit dem nächsten regulären Release.

# Tech-Spec

- crm.dsj.ch erscheint bei der Suche in gängigen Internet-Suchmaschinen nicht mehr
- kein spezifischer Release

# ToDo

- [x] robotos.txt-File erstellen
- [x] Inhalt für robotos.txt-File definieren
- [x] Auf Integration testen ob das robots.txt File aus dem Wagon unter der korrekten URL erscheint

**Comment by kronn** [comment]
Durch die Umstellung auf Ruby3 und den neuen Build-Ansatz musste die Anpassung in die OpenShift-Config übernommen werden. 

https://gitlab.puzzle.ch/pitc_hit/hitobito-configmanagement/-/commit/a6ca821e04fdd7f32bc64b31dfffcab3ee8c28fa
-> https://dsj.puzzle.ch/robots.txt
