### ISSUE TITLE
EPIC: Anpassungen 2021

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_dsj#7]
Übersicht der Erweiterungen für die DSJ im 2021

- [x] Tags -> Filtern nach Tag in der Personenliste, bereits vorhanden
- [ ]  Anpassungen an dem Firmen Konzept https://github.com/hitobito/hitobito_dsj/issues/8 1PT
- [ ]  Auswahl Geschlecht mit "Divers" ergänzen. https://github.com/hitobito/hitobito_dsj/issues/12 1PT
- [ ] Auf einer Person mehrere Firmen angeben https://github.com/hitobito/hitobito_dsj/issues/9 3PT
- [ ] Attribute von einem Jugendparlament ergänzen: https://github.com/hitobito/hitobito_dsj/issues/10 1PT
- [ ] Berechtigung Notizen auf einer Organisation https://github.com/hitobito/hitobito_dsj/issues/11 1PT
- [ ] Prod Release 0.5PT

**Comment by ThomasEllenberger** [comment]
Dieses Anliegen ist bei der DSJ aktuell kein Thema mehr.
Wird vorerst als nicht geplant geschlossen.
